name: telegram_web_app_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/RuslanTsitser/telegram_web_app_client

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  js: ^0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
